import type { Metadata } from "next";
import "./globals.css";
import ConditionalFooter from '@/components/home/ConditionalFooter'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans">
        <ThemeProvider
          defaultTheme="system"
          storageKey="smart-library-theme"
        >
          {children}
          <ConditionalFooter/>
        </ThemeProvider>
      </body>
    </html>
  );
}

